permalink: /:year/:month/:day/:title
markdown: kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
paginate: 5
paginate_path: "news/page/:num"
excerpt_separator: "\n\n\n"

title : ConfuserEx 2
description: ConfuserEx 2 is an open-source protector for .NET applications.
repo : "https://github.com/mkaring/ConfuserEx"
author:
  name: Martin Karing
  email: karing.martin@gmail.com

production_url: //mkaring.github.io/ConfuserEx

JB :
  version : 0.3.0
  BASE_PATH : //mkaring.github.io/ConfuserEx

  ASSET_PATH : false

  archive_path: /archive/
  atom_path : /atom.xml
  rss_path : /rss.xml
theme: jekyll-theme-slate