version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_commits:
  files:
  - doc/*
  - readme.md
  - license.md

nuget:
  disable_publish_on_pr: true

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: msbuild Confuser2.sln /t:Restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build:
  project: Confuser2.sln
  verbosity: minimal

artifacts:
- path: Release/bin
  name: ConfuserEx
  type: zip
- path: Confuser.MSBuild.Tasks/bin/Release/*.nupkg
  name: ConfuserEx.MSBuild

for:
-
  branches:
    except:
      - master

  build:
    publish_nuget: false

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "ConfuserEx $(APPVEYOR_REPO_TAG_NAME) Release"
  provider: GitHub
  auth_token:
    secure: NTT+Z1zBxbj+w8jroqhYJnI2urxSt0gq3MUmDavUPVKZL+YX4krR4xJQ5OmHYhcG
  on:
    APPVEYOR_REPO_TAG: true

deploy:
  provider: NuGet
  api_key:
    secure: g1HSOpBz5QurbLPHE06OFyRLxK7HF8Q88mk6dh3ifG7dULhsampXh07ZR+VBhj8iW
  on:
    APPVEYOR_REPO_TAG: true