version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_commits:
  files:
  - doc/*
  - readme.md
  - license.md

nuget:
  disable_publish_on_pr: true

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: msbuild Confuser2.sln @appveyor_restore.rsp /m

build:
  project: Confuser2.sln
  verbosity: minimal 
  parallel: true

after_test:
- cmd: msbuild Confuser.CLI\Confuser.CLI.csproj -v:m -t:Restore;Publish -p:Configuration=Release -p:TargetFramework=netcoreapp2.2 -p:RuntimeIdentifier=linux-x64 -p:RestoreRecursive=false -p:PublishDir=../Publish/linux-x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: msbuild Confuser.CLI\Confuser.CLI.csproj -v:m -t:Restore;Publish -p:Configuration=Release -p:TargetFramework=netcoreapp2.2 -p:RuntimeIdentifier=osx-x64 -p:RestoreRecursive=false -p:PublishDir=../Publish/osx-x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: msbuild Confuser.CLI\Confuser.CLI.csproj -v:m -t:Restore;Publish -p:Configuration=Release -p:TargetFramework=netcoreapp2.2 -p:RuntimeIdentifier=win-x64 -p:RestoreRecursive=false -p:PublishDir=../Publish/win-x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: msbuild Confuser.CLI\Confuser.CLI.csproj -v:m -t:Restore;Publish -p:Configuration=Release -p:TargetFramework=netcoreapp2.2 -p:RuntimeIdentifier=win-x86 -p:RestoreRecursive=false -p:PublishDir=../Publish/win-x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: Release/bin
  name: ConfuserEx
  type: zip
- path: Publish/linux-x64
  name: ConfuserEx (Linux x64)
  type: zip
- path: Publish/osx-x64
  name: ConfuserEx (Mac OS X x64)
  type: zip
- path: Publish/win-x64
  name: ConfuserEx (Windows x64)
  type: zip
- path: Publish/win-x32
  name: ConfuserEx (Windows x32)
  type: zip

for:
-
  branches:
    only:
      - master

  artifacts:
  - path: Confuser.MSBuild.Tasks/bin/Release/*.nupkg
    name: ConfuserEx.MSBuild

on_failure:
- appveyor PushArtifact msbuild.binlog

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/7ff0ea601d40c1b3fcaa
  on_build_success: true
  on_build_failure: true

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "ConfuserEx $(APPVEYOR_REPO_TAG_NAME) Release"
  provider: GitHub
  auth_token:
    secure: NTT+Z1zBxbj+w8jroqhYJnI2urxSt0gq3MUmDavUPVKZL+YX4krR4xJQ5OmHYhcG
  on:
    APPVEYOR_REPO_TAG: true
