version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_commits:
  files:
  - doc/*
  - readme.md
  - license.md

nuget:
  disable_publish_on_pr: true
  
install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: msbuild Confuser2.sln @appveyor_restore.rsp /m

build:
  project: Confuser2.sln
  verbosity: minimal 
  parallel: true
  publish_core_console: true

artifacts:
- path: Release/bin
  name: ConfuserEx
  type: zip
  
for:
-
  branches:
    only:
      - master

  artifacts:
  - path: Confuser.MSBuild.Tasks/bin/Release/*.nupkg
    name: ConfuserEx.MSBuild

on_failure:
- appveyor PushArtifact msbuild.binlog

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/7ff0ea601d40c1b3fcaa
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
